version: "3"
services:
    node:
        build:
            context: ./
        tty: true
        volumes:
            - ./apps/api:/usr/src/app
        ports:
            - "8080:8080"
    react:
        build:
            context: ./
        tty: true
        volumes:
            - ./apps/webapp:/usr/src/app
        ports:
            - "3000:3000"

    db:
        image: mariadb
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: ${DBPSWD}
            MYSQL_DATABASE: main
        volumes:
            - "./data:/var/lib/mysql"

    adminer:
        image: adminer
        restart: on-failure
        ports:
            - "8081:8080"
